version: 2.1

jobs:
  testAndLint:
    docker:
      - image: cimg/node:20.3.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run Tests
          command: npm run test
      - run:
          name: Run Linter
          command: npm run lint

  deploy:
    docker:
      - image: cimg/node:20.3.0

    steps:
      - checkout

      # Set up SSH keys for deployment
      - add_ssh_keys:
          fingerprints:
            - "34:cc:96:6f:42:7f:9f:02:cf:07:36:92:d0:f9:06:fe"

      # Install dependencies and build your application
      - run:
          name: Install Dependencies
          command: |
            # Add your dependency installation commands for Node.js

      # Deploy to EC2 instance
      - run:
          name: Deploy to EC2
          command: |
            ssh -o StrictHostKeyChecking=no ubuntu@ec2-18-212-14-214.compute-1.amazonaws.com 'echo "Hello, world!"'

workflows:
  test-deploy:
    jobs:
      - testAndLint
      - deploy:
          requires:
            - testAndLint