version: 2.1

jobs:
  testAndLint:
    docker:
      - image: cimg/node:20.3.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run Tests
          command: npm run test
      - run:
          name: Run Linter
          command: npm run lint

  deploy:
    docker:
      - image: circleci/python:3.7
    steps:
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Install AWS CLI
          command: |
            curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
            unzip awscli-bundle.zip
            sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
      - run:
          name: Deploy Over SSH
          command: |
            # Rest of your deployment commands here

workflows:
  test-deploy:
    jobs:
      - testAndLint
      - deploy:
          requires:
            - testAndLint