version: 2.1
#
jobs:
  testAndLint:
    docker:
      - image: cimg/node:20.3.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run Tests
          command: npm run test
      - run:
          name: Run Linter
          command: npm run lint
      - persist_to_workspace:
          root: .
          paths:
            - client/dist
            - server
            - package-lock.json
            - package.json

  deploy:
    docker:
      - image: cimg/node:20.3.0

    steps:
      - checkout
      - attach_workspace:
          at: .

      # Deploy to EC2 instance
      - run:
          name: Deploy to EC2
          command: |
            scp -o StrictHostKeyChecking=no server package-lock.json package.json ubuntu@ec2-18-212-14-214.compute-1.amazonaws.com:~/production
            scp -o StrictHostKeyChecking=no -r client/dist ubuntu@ec2-18-212-14-214.compute-1.amazonaws.com:~/production/client

            ssh -o StrictHostKeyChecking=no ubuntu@ec2-18-212-14-214.compute-1.amazonaws.com '
              cd ~/production
              npm install
              npm run server-restart
            '
workflows:
  test-deploy:
    jobs:
      - testAndLint
      - deploy:
          requires:
            - testAndLint